from datetime import datetime
import random

import seaborn as sns
import numpy as np
import shap
import torch
from torch.utils.data import DataLoader
import matplotlib.pylab as plt
import matplotlib as mpl
from scipy.stats import spearmanr
from matplotlib.colors import TwoSlopeNorm

# we have more than 20 sensors! need to expand color cycle
colors = list(plt.cm.tab20.colors) + list(plt.cm.tab20b.colors)
mpl.rcParams['axes.prop_cycle'] = mpl.cycler(color=colors)

from model import AutoEncoder, Encoder
from dataset import AggregateIVDatasetForAutoEncoder, AggregateLatentDataset
from utils import Sensor, DATABASE_DIR, load_model_from_pth


def get_full_dataset():
    if not hasattr(get_full_dataset, "_dataset"):
        print("Initializing dataset...")
        get_full_dataset._dataset = AggregateIVDatasetForAutoEncoder(DATABASE_DIR, mode="full")
    return get_full_dataset._dataset


def get_compact_dataset():
    if not hasattr(get_compact_dataset, "_dataset"):
        print("Initializing dataset...")
        get_compact_dataset._dataset = AggregateIVDatasetForAutoEncoder(DATABASE_DIR, mode="compact")
    return get_compact_dataset._dataset

def explain_latent_on_data(model_path: str, dim: int = None, num_samples: int = None):
    """
    Run SHAP analysis on latents generated by autoencoder. Plot IV curves 
    colored with SHAP values.
    
    Parameters
    ----------
    model_path : str
        The relative path to autoencoder model.
    dim : int, optional
        Which dim of the latent space to examine. If not specified, plots all dims.
    num_samples : int, optional
        Number of IV curves to plot.
    """

    if torch.cuda.is_available():
        device = torch.device("cuda")
    elif torch.backends.mps.is_available():
        device = torch.device("mps")
    else:
        device = torch.device("cpu")

    print(f"Using device: {device}")

    dataset = get_compact_dataset()

    model = load_model_from_pth(model_path, "Encoder", dataset.max_seq_len, device)
    model.eval()

    if dim is not None:
        assert 0 <= dim < model.latent_dim
        dims = [dim]
    else:
        dims = [i for i in range(model.latent_dim)]

    if num_samples is None:
        num_samples = len(dataset) - 300

    print("Computing SHAP on background..")
    # select a set of background examples to take an expectation over
    background_idx = set(random.sample(range(len(dataset)), k=len(dataset) - num_samples))
    background = [dataset[i][0] for i in background_idx]  # take i curve only
    background = torch.stack(background, dim=0).float().to(device)
    e = shap.GradientExplainer(model, background)

    print("Computing SHAP on inputs to explain..")
    input_to_explain = [dataset[i] for i in range(len(dataset)) if i not in background_idx]
    iv_curves_to_explain = [out[0] for out in input_to_explain]
    seq_lens = [out[1] for out in input_to_explain]
    iv_curves_to_explain = torch.stack(iv_curves_to_explain, dim=0).float().to(device)

    # explain output of the encoder
    shap_values = e.shap_values(iv_curves_to_explain)  # shape (num_samples, 1, max_seq_len, latent_dim)

    volt_grid = np.arange(0, 400, 1)
    norm = TwoSlopeNorm(vmin=-np.abs(shap_values).max() / 7, vcenter=0, vmax=np.abs(shap_values).max() / 7)
    for dim in dims:
        plt.figure(figsize=(14, 10))
        for i in range(num_samples):
            plt.scatter(volt_grid[:seq_lens[i]], iv_curves_to_explain[i, 1, :seq_lens[i]].cpu().detach().squeeze(),
                        c=shap_values[i, 0, :seq_lens[i], dim].squeeze(), cmap=plt.get_cmap("RdBu").reversed(),
                        norm=norm)
        plt.ylim(bottom=-20)
        plt.title(f"SHAP Values on Dim {dim} on Training Data")
        plt.xlabel("Reverse Bias Voltage (V)")
        plt.ylabel("log(Pad Current (A))")
        plt.colorbar(label=f"SHAP Values on Dim {dim}")
        plt.tight_layout()
        plt.savefig(model_path.replace(".pth", f"dim{dim}.png"))
        # plt.show()
        plt.close()


def explain_latent_corr(model_path: str):
    """
    Compute Spearman Correlation Coefficient for every pair of environmental 
    variables and latent dims. Generate a heatmap. Values closer to 1 mean 
    stronger monotonic relation, and closer to 0 means no obvious monotonic 
    relation. The coefficients are not absolute, and hence should be compared across 
    different pairs.
    
    Parameters
    ----------
    model_path : str
        The relative path to autoencoder model.
    """
    dataset = AggregateLatentDataset(DATABASE_DIR, model_path, data_config_path="./ml_data_config.txt")

    selected_metrics = [0, 1, 3, 4, 5, 8]
    X = [torch.tensor([dataset[i][j] for j in selected_metrics]) for i in range(len(dataset))]  # metrics
    Y = [dataset[i][-1].squeeze() for i in range(len(dataset))]  # latents
    X = torch.stack(X, dim=0)
    Y = torch.stack(Y, dim=0)

    corr_matrix = np.zeros((6, Y.shape[1]))
    for i in range(X.shape[1]):
        for j in range(Y.shape[1]):
            corr_matrix[i, j], _ = spearmanr(X[:, i], Y[:, j])

    plt.figure(figsize=(16, 6))
    input_names = ["Temperature", "Date", "Humidity", "Ramp Type", "Duration", "Sensor Number"]
    norm = TwoSlopeNorm(vmin=-1, vcenter=0, vmax=1)
    sns.heatmap(corr_matrix, annot=True, cmap=plt.get_cmap("RdBu").reversed(),
                yticklabels=[input_names[i] for i in range(corr_matrix.shape[0])],
                xticklabels=[f"Dim {j}" for j in range(corr_matrix.shape[1])],
                fmt=".2f", norm=norm)
    plt.xlabel("Latent Dimensions")
    plt.ylabel("Environmental Conditions")
    plt.title("Spearman Correlation Coefficients")
    plt.tight_layout()
    # plt.show()
    plt.savefig(model_path.replace(".pth", f"corr.png"))


def compare_mlp_vs_ground_truth_latent(autoencoder_model_path: str, mlp_model_path: str, latent_dim: int, is_conditional: bool=False):
    """
    Compare MLP-predicted latent vectors with ground truth latent vectors from autoencoder.
    Generate plots showing both predicted and ground truth latents overlaid and annotated by environmental variables.
    
    Parameters
    ----------
    autoencoder_model_path : str
        The relative path to the autoencoder model that generates ground truth latents.
    mlp_model_path : str
        The relative path to the MLP model that predicts latents from environmental variables.
    is_conditional : bool, optional
        Whether the MLP model is conditional. Defaults to False.

    Notes
    -----
    Creates scatter plots overlaying MLP predictions over ground truth for different latent dimensions,
    colored by environmental variables. Plots are saved to the MLP model's directory.
    """
    if torch.cuda.is_available():
        device = torch.device("cuda")
    elif torch.backends.mps.is_available():
        device = torch.device("mps")
    else:
        device = torch.device("cpu")

    print(f"Using device: {device}")

    # Load the latent dataset (contains ground truth latents from autoencoder)
    from model import EnvToLatent
    dataset = AggregateLatentDataset(DATABASE_DIR, autoencoder_model_path, is_conditional=is_conditional, data_config_path="./ml_data_config.txt")
    
    # Load MLP model
    mlp_model = EnvToLatent().to(device)
    mlp_model.load_state_dict(torch.load(mlp_model_path, map_location=device))
    mlp_model.eval()
    
    # Collect data
    all_gt_latent = []  # ground truth latents
    all_pred_latent = []  # MLP predicted latents
    all_temp = []
    all_humi = []
    all_ramp = []
    all_sensor_num = []
    all_sensor_thickness = []
    all_sensor_type = []
    
    with torch.no_grad():
        for temp, date, iv_seq, humi, ramp_type, dura, seq_len, bd_v, sensor_num, sensor_name, sensor_thickness, sensor_type, gt_latent in dataset:
            # Ground truth latent (from autoencoder)
            all_gt_latent.append(gt_latent.squeeze())
            
            # Predict latent using MLP
            # metrics = torch.tensor([temp, date, humi, ramp_type, dura, sensor_num]).float().to(device).unsqueeze(0)
            metrics = torch.tensor([temp, humi, ramp_type, sensor_num, sensor_thickness, sensor_type]).float().to(device).unsqueeze(0)
            pred_latent = mlp_model(metrics)
            all_pred_latent.append(pred_latent.cpu().squeeze())
            
            # Environmental variables
            all_temp.append(temp if temp is not None else float('nan'))
            all_humi.append(humi if humi is not None else float('nan'))
            all_ramp.append(ramp_type if ramp_type is not None else float('nan'))
            all_sensor_num.append(sensor_num)
            all_sensor_thickness.append(sensor_thickness if sensor_thickness is not None else float('nan'))
            all_sensor_type.append(sensor_type if sensor_type is not None else float('nan'))

    all_gt_latent = np.array(all_gt_latent)
    all_pred_latent = np.array(all_pred_latent)
    
    print(f"Comparing {all_gt_latent.shape[0]} latents of {all_gt_latent.shape[1]} dimensions.")
    print(f"Ground truth latent shape: {all_gt_latent.shape}")
    print(f"Predicted latent shape: {all_pred_latent.shape}")

    params = ["Temperature (C)", "Humidity (%)", "Ramp Type", "Sensor Number", "Sensor Thickness (μm)", "Sensor Type"]
    value_lsts = [all_temp, all_humi, all_ramp, all_sensor_num, all_sensor_thickness, all_sensor_type]
    value_lsts = [np.array(lst) for lst in value_lsts]

    # Create output directory
    import os
    mlp_dir = os.path.dirname(mlp_model_path)
    
    # Plot different latent dimensions
    dim_pairs = [(0, 6), (1, 7), (2, 8), (3, 9)]  # Compare different dimension pairs
    if latent_dim <= 4:
        dim_pairs = [(0, 1), (0, 2), (1, 2), (0, 3)]
    for dim_1, dim_2 in dim_pairs:
        fig_idx = 0
        for param, value_lst in zip(params, value_lsts):
            plt.figure(figsize=(14, 10))
            
            if param == "Ramp Type":
                ramp_map = {-1: "Down", 0: "NA", 1: "Up"}
                for ramp_type in np.unique(value_lst):
                    mask = (value_lst == ramp_type)
                    # Plot ground truth with circles and lower alpha
                    plt.scatter(all_gt_latent[mask][:, dim_1], all_gt_latent[mask][:, dim_2], 
                              label=f"GT {ramp_map[ramp_type]}", alpha=0.6, s=60, marker='o', edgecolors='black', linewidth=0.5)
                    # Plot predictions with X markers and higher alpha
                    plt.scatter(all_pred_latent[mask][:, dim_1], all_pred_latent[mask][:, dim_2], 
                              label=f"Pred {ramp_map[ramp_type]}", alpha=0.9, s=40, marker='x', linewidth=2)
                plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')

            elif param == "Sensor Type":
                type_map = {0: "DC", 1: "AC"}
                for sensor_type in np.unique(value_lst):
                    if not np.isnan(sensor_type):
                        mask = (value_lst == sensor_type)
                        type_label = type_map.get(int(sensor_type), f"Type {int(sensor_type)}")
                        # Plot ground truth with circles
                        plt.scatter(all_gt_latent[mask][:, dim_1], all_gt_latent[mask][:, dim_2],
                                  label=f"GT {type_label}", alpha=0.6, s=60, marker='o', edgecolors='black', linewidth=0.5)
                        # Plot predictions with X markers
                        plt.scatter(all_pred_latent[mask][:, dim_1], all_pred_latent[mask][:, dim_2],
                                  label=f"Pred {type_label}", alpha=0.9, s=40, marker='x', linewidth=2)
                plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')

            elif param == "Sensor Number":
                for sensor_num in np.unique(value_lst):
                    mask = (value_lst == sensor_num)
                    sensor_name = dataset.sensor_number_to_name[sensor_num]
                    # Plot ground truth with circles
                    plt.scatter(all_gt_latent[mask][:, dim_1], all_gt_latent[mask][:, dim_2],
                              label=f"GT {sensor_name}", alpha=0.6, s=60, marker='o', edgecolors='black', linewidth=0.5)
                    # Plot predictions with X markers
                    plt.scatter(all_pred_latent[mask][:, dim_1], all_pred_latent[mask][:, dim_2],
                              label=f"Pred {sensor_name}", alpha=0.9, s=40, marker='x', linewidth=2)
                plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')

            else:  # continuous variables (Temperature, Humidity, Sensor Thickness)
                # Plot ground truth with circles
                sc1 = plt.scatter(all_gt_latent[:, dim_1], all_gt_latent[:, dim_2], c=value_lst, 
                                cmap="rainbow", alpha=0.6, s=60, marker='o', edgecolors='black', linewidth=0.5, label="Ground Truth")
                # Plot predictions with X markers
                sc2 = plt.scatter(all_pred_latent[:, dim_1], all_pred_latent[:, dim_2], c=value_lst, 
                                cmap="rainbow", alpha=0.9, s=40, marker='x', linewidth=2, label="MLP Prediction")
                
                plt.colorbar(sc1, label=param)
                plt.legend()

            plt.title(f"Ground Truth vs MLP Predicted Latent Space\nDim {dim_2} vs {dim_1} (Colored by {param})")
            plt.xlabel(f"Latent Dim {dim_1}")
            plt.ylabel(f"Latent Dim {dim_2}")
            
            plt.tight_layout()
            save_path = os.path.join(mlp_dir, f"overlay_comparison_dim{dim_2}_{dim_1}_{param.replace(' ', '_').replace('(', '').replace(')', '').replace('μ', 'u')}.png")
            plt.savefig(save_path, dpi=150, bbox_inches='tight')
            plt.show()
            plt.close()
            fig_idx += 1
    
    # Also create correlation plots between GT and predicted latents
    plt.figure(figsize=(15, 10))
    for i in range(min(18, all_gt_latent.shape[1])):  # Plot first 18 dimensions or all if fewer
        plt.subplot(3, 6, i+1)
        plt.scatter(all_gt_latent[:, i], all_pred_latent[:, i], alpha=0.6, s=20)
        
        # Add diagonal line for perfect prediction
        min_val = min(all_gt_latent[:, i].min(), all_pred_latent[:, i].min())
        max_val = max(all_gt_latent[:, i].max(), all_pred_latent[:, i].max())
        plt.plot([min_val, max_val], [min_val, max_val], 'r--', alpha=0.8, linewidth=1)
        
        # Calculate correlation
        corr_coef = np.corrcoef(all_gt_latent[:, i], all_pred_latent[:, i])[0, 1]
        plt.title(f"Dim {i}\nr={corr_coef:.3f}")
        plt.xlabel("Ground Truth")
        plt.ylabel("MLP Predicted")
        
    plt.suptitle("Ground Truth vs MLP Predicted Latents\n(Red line = perfect prediction)", fontsize=14)
    plt.tight_layout()
    save_path = os.path.join(mlp_dir, "gt_vs_pred_correlation.png")
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()
    plt.close()
    
    print(f"Comparison plots saved to: {mlp_dir}")


if __name__ == '__main__':
    # model_path = "autoencoder_model/ivcvscans-2025-08-12-03-24-52/e125_l15.918.pth"
    # mlp_path = "env_to_latent_model/ivcvscans-2025-08-12-14-10-45/e133_l0.178.pth"
    # mlp_path = "env_to_latent_model/ivcvscans-2025-10-13-08-52-22-e2e/e82_l1.162.pth"
    # mlp_path = "env_to_latent_model/ivcvscans-2025-10-13-09-09-32-e2e/e81_l2.403.pth"
    
    # model_path = "conditional_autoencoder_model/ivcvscans-2025-10-13-09-31-32/e105_l0.300.pth"
    # mlp_path = "env_to_latent_model/ivcvscans-2025-10-13-09-59-07-e2e/e63_l4.837.pth"

    # model_path = "conditional_autoencoder_model/ivcvscans-2025-10-13-10-37-16/e93_l13.541.pth"
    # mlp_path = "env_to_latent_model/ivcvscans-2025-10-13-11-05-23-e2e/e81_l2.623.pth"
    
    
    # model_path = "conditional_autoencoder_model/ivcvscans-2025-10-13-11-59-29/e108_l0.332.pth"
    # mlp_path = "env_to_latent_model/ivcvscans-2025-10-13-12-08-01-e2e/e60_l3.557.pth"
    
    # model_path = "conditional_autoencoder_model/ivcvscans-2025-10-13-14-25-08/e97_l0.269.pth" # latent 16 + params 6
    # mlp_path = "env_to_latent_model/ivcvscans-2025-10-13-14-38-28-e2e/e86_l3.081.pth"
    
    # model_path = "conditional_autoencoder_model/ivcvscans-2025-10-28-10-30-59/e95_l0.211.pth" # latent 8 + params 6
    # mlp_path = "env_to_latent_model/ivcvscans-2025-10-28-10-43-53-e2e/e108_l4.887.pth"
    
    model_path = "conditional_autoencoder_model/ivcvscans-2025-10-28-11-02-38/e97_l0.305.pth" # latent 4 + params 6
    mlp_path = "env_to_latent_model/ivcvscans-2025-10-28-11-15-26-e2e/e120_l6.899.pth"

    compare_mlp_vs_ground_truth_latent(model_path, mlp_path, latent_dim=4, is_conditional=True)
